"use client";

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { PropsWithChildren } from "react";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

const queryClient = new QueryClient({
  defaultOptions: {
    mutations: { retry: 3, retryDelay: 2000 },
    queries: { retry: 2, retryDelay: 2000 },
  },
});

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
          {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
